"""Tests for h2iso-based ISS initialization helper.

These tests verify the pure-Python conversion and generation functions
without requiring h2iso or OpenModelica installed.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

SCRIPT_DIR = Path(__file__).resolve().parents[2] / "script" / "distillation"
sys.path.insert(0, str(SCRIPT_DIR))

from init_from_h2iso import (  # noqa: E402
    TRICYS_SPECIES,
    _set_parameter_line,
    generate_column_mos,
    generate_init_all_mos,
    h2iso_to_tricys_composition,
)


class TestH2isoToTricysComposition:
    """Tests for h2iso_to_tricys_composition conversion."""

    def test_normal_composition(self):
        """6-component input should map to 5-component output."""
        # h2iso: [H2, HD, HT, D2, DT, T2]
        comp_6 = [0.1, 0.2, 0.1, 0.2, 0.2, 0.2]
        result = h2iso_to_tricys_composition(comp_6)
        assert len(result) == 5
        assert abs(sum(result) - 1.0) < 1e-12
        # H2 unchanged
        assert abs(result[0] - 0.1) < 1e-12
        # HD + HT lumped
        assert abs(result[1] - 0.3) < 1e-12
        # D2, DT, T2 unchanged
        assert abs(result[2] - 0.2) < 1e-12
        assert abs(result[3] - 0.2) < 1e-12
        assert abs(result[4] - 0.2) < 1e-12

    def test_pure_h2(self):
        """Pure H2 should map to [1, 0, 0, 0, 0]."""
        comp_6 = [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        result = h2iso_to_tricys_composition(comp_6)
        assert result == [1.0, 0.0, 0.0, 0.0, 0.0]

    def test_pure_t2(self):
        """Pure T2 should map to [0, 0, 0, 0, 1]."""
        comp_6 = [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
        result = h2iso_to_tricys_composition(comp_6)
        assert result == [0.0, 0.0, 0.0, 0.0, 1.0]

    def test_all_zeros(self):
        """All zeros should return all zeros (no division by zero)."""
        comp_6 = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        result = h2iso_to_tricys_composition(comp_6)
        assert result == [0.0, 0.0, 0.0, 0.0, 0.0]

    def test_negative_clamp(self):
        """Negative values should be clamped to zero and renormalized."""
        comp_6 = [-0.01, 0.3, -1e-15, 0.2, 0.3, 0.2]
        result = h2iso_to_tricys_composition(comp_6)
        assert all(x >= 0 for x in result)
        assert abs(sum(result) - 1.0) < 1e-12
        # H2 clamped to 0
        assert result[0] == 0.0
        # HT: only HD contributes (HT clamped)
        assert abs(result[1] - 0.3) < 1e-12

    def test_small_negative_artifact(self):
        """Small negative float artifacts (-1e-16) should be clamped."""
        comp_6 = [0.2, 0.2, -1e-16, 0.2, 0.2, 0.2]
        result = h2iso_to_tricys_composition(comp_6)
        assert all(x >= 0 for x in result)
        assert abs(sum(result) - 1.0) < 1e-12


class TestSetParameterLine:
    """Tests for _set_parameter_line formatting."""

    def test_basic_format(self):
        """Should produce valid setParameterValue command."""
        line = _set_parameter_line("CD1", "N_stages", "50")
        assert line.startswith("setParameterValue(")
        assert line.endswith(";")
        assert 'model="CD1"' in line
        assert 'parameter="N_stages"' in line
        assert "value=50" in line


class TestGenerateColumnMos:
    """Tests for generate_column_mos output."""

    def test_output_structure(self):
        """Generated .mos should contain expected sections."""
        top_comp = [0.1, 0.2, 0.1, 0.2, 0.2, 0.2]
        bot_comp = [0.05, 0.15, 0.1, 0.3, 0.2, 0.2]
        content = generate_column_mos(
            col_name="CD1",
            n_stages=40,
            top_composition=top_comp,
            bottom_composition=bot_comp,
            top_temperature=25.0,
            bottom_temperature=28.5,
            distillate_flow=10.0,
            bottoms_flow=5.0,
            reflux_ratio=15.0,
        )
        assert "Initialization script for column CD1" in content
        assert "Generated by h2iso flowsheet solver" in content
        assert "// Column parameters" in content
        assert 'setParameterValue(model="CD1"' in content
        assert 'parameter="N_stages", value=40' in content
        assert 'parameter="R", value=15.0000' in content
        # Distillate section
        assert "// Distillate (top product)" in content
        assert 'F_distillate' in content
        assert 'T_top' in content
        assert 'x_top[1]' in content
        assert 'x_top[5]' in content
        # Bottoms section
        assert "// Bottoms (bottom product)" in content
        assert 'F_bottoms' in content
        assert 'T_bottom' in content
        assert 'x_bottom[1]' in content
        assert 'x_bottom[5]' in content

    def test_line_count(self):
        """Should produce a reasonable number of lines."""
        ones = [1.0 / 6] * 6
        content = generate_column_mos(
            col_name="CD1",
            n_stages=40,
            top_composition=ones,
            bottom_composition=ones,
            top_temperature=25.0,
            bottom_temperature=28.5,
            distillate_flow=10.0,
            bottoms_flow=5.0,
            reflux_ratio=15.0,
        )
        lines = content.strip().split("\n")
        # ~3 header + 2 params + 1 blank + 1 section + 3 callouts + 5 x_top
        # + 1 blank + 1 section + 3 callouts + 5 x_bottom + 1 blank = ~26
        assert len(lines) >= 20

    def test_trivial_input(self):
        """Should work with trivial input without error."""
        ones = [1.0 / 6] * 6
        content = generate_column_mos(
            col_name="TST",
            n_stages=1,
            top_composition=ones,
            bottom_composition=ones,
            top_temperature=20.0,
            bottom_temperature=20.0,
            distillate_flow=1.0,
            bottoms_flow=1.0,
            reflux_ratio=1.0,
        )
        assert 'model="TST"' in content


class TestGenerateInitAllMos:
    """Tests for generate_init_all_mos master script."""

    def test_single_column(self):
        """Single column should generate one runScript call."""
        content = generate_init_all_mos(["CD1"])
        assert 'runScript("CD1_init.mos");' in content
        assert "ISS column initialization complete" in content

    def test_multiple_columns(self):
        """Multiple columns should generate multiple runScript calls."""
        content = generate_init_all_mos(["CD1", "CD2", "CD3"])
        assert 'runScript("CD1_init.mos");' in content
        assert 'runScript("CD2_init.mos");' in content
        assert 'runScript("CD3_init.mos");' in content

    def test_empty_list(self):
        """Empty column list should produce header-only output."""
        content = generate_init_all_mos([])
        assert "Master initialization" in content
        assert "runScript" not in content


class TestTricysSpecies:
    """Verify TRICYS_SPECIES constant correctness."""

    def test_species_order(self):
        """5-component vector should follow [H2, HD_HT, D2, DT, T2]."""
        assert TRICYS_SPECIES == ["H2", "HD_HT", "D2", "DT", "T2"]

    def test_species_count(self):
        """TRICYS uses exactly 5 components."""
        assert len(TRICYS_SPECIES) == 5
