"""Generate Modelica initialization scripts from h2iso flowsheet solution.

This script solves a multi-column hydrogen isotope separation flowsheet
using h2iso and outputs .mos (Modelica script) files that set initial
values for the corresponding tricys Modelica models.

Usage:
    python init_from_h2iso.py --config <flowsheet.json> [--output <dir>]

Requirements:
    pip install "h2iso[solver]>=0.1.0"
"""

from __future__ import annotations

import argparse
import json
import sys
from importlib import import_module
from pathlib import Path


def _load_h2iso_dependencies():
    """Import h2iso solver dependencies after CLI parsing.

    Keeping these imports lazy allows ``--help`` and argument validation to
    work even when the optional distillation dependency is not installed.
    """
    try:
        schema_module = import_module("h2iso.flowsheet.schema")
        solver_module = import_module("h2iso.flowsheet.solver")
    except ImportError as exc:
        missing_name = getattr(exc, "name", "") or ""
        if missing_name.startswith("h2iso"):
            reason = "h2iso is not installed"
        elif missing_name == "casadi":
            reason = "h2iso solver extra is not installed (missing casadi)"
        else:
            reason = f"h2iso dependency import failed: {exc}"
        print(
            f"Error: {reason}. Install with:\n"
            "  pip install \"h2iso[solver]>=0.1.0\"\n"
            "Or from source:\n"
            "  pip install -e /path/to/h2iso[solver]",
            file=sys.stderr,
        )
        raise SystemExit(1) from exc
    return schema_module.load_flowsheet, solver_module.SequentialModularSolver


# Mapping from h2iso species to tricys 5-component vector
# tricys uses [H2, HD+HT, D2, DT, T2] (5-dim)
# h2iso uses [H2, HD, HT, D2, DT, T2] (6-dim)
TRICYS_SPECIES = ["H2", "HD_HT", "D2", "DT", "T2"]


def _set_parameter_line(model_name: str, parameter: str, value: str) -> str:
    """Return an OpenModelica setParameterValue command."""
    return (
        f'setParameterValue(model="{model_name}", '
        f'parameter="{parameter}", value={value});'
    )


def h2iso_to_tricys_composition(comp_6: list[float]) -> list[float]:
    """Convert h2iso 6-component to tricys 5-component composition.

    tricys lumps HD and HT together as the second component.
    Clamps negative floating-point artifacts to zero.
    """
    result = [
        max(0.0, comp_6[0]),              # H2
        max(0.0, comp_6[1] + comp_6[2]),  # HD + HT
        max(0.0, comp_6[3]),              # D2
        max(0.0, comp_6[4]),              # DT
        max(0.0, comp_6[5]),              # T2
    ]
    # Normalize to ensure sum = 1
    total = sum(result)
    if total > 0:
        result = [x / total for x in result]
    return result


def generate_column_mos(
    col_name: str,
    n_stages: int,
    top_composition: list[float],
    bottom_composition: list[float],
    top_temperature: float,
    bottom_temperature: float,
    distillate_flow: float,
    bottoms_flow: float,
    reflux_ratio: float,
) -> str:
    """Generate .mos script content for a single column.

    The script sets initial values for a tricys ISS column model.
    """
    top_5 = h2iso_to_tricys_composition(top_composition)
    bot_5 = h2iso_to_tricys_composition(bottom_composition)

    lines = [
        f"// Initialization script for column {col_name}",
        "// Generated by h2iso flowsheet solver",
        "// Do not edit manually — regenerate with init_from_h2iso.py",
        "",
        "// Column parameters",
        _set_parameter_line(col_name, "N_stages", str(n_stages)),
        _set_parameter_line(col_name, "R", f"{reflux_ratio:.4f}"),
        "",
        "// Distillate (top product)",
        _set_parameter_line(
            col_name,
            "F_distillate",
            f"{distillate_flow:.4f}",
        ),
        _set_parameter_line(col_name, "T_top", f"{top_temperature:.4f}"),
    ]

    for i, _ in enumerate(TRICYS_SPECIES):
        lines.append(
            _set_parameter_line(col_name, f"x_top[{i + 1}]", f"{top_5[i]:.8f}")
        )

    lines.extend([
        "",
        "// Bottoms (bottom product)",
        _set_parameter_line(col_name, "F_bottoms", f"{bottoms_flow:.4f}"),
        _set_parameter_line(col_name, "T_bottom", f"{bottom_temperature:.4f}"),
    ])

    for i, _ in enumerate(TRICYS_SPECIES):
        lines.append(
            _set_parameter_line(
                col_name,
                f"x_bottom[{i + 1}]",
                f"{bot_5[i]:.8f}",
            )
        )

    lines.append("")
    return "\n".join(lines)


def generate_init_all_mos(column_names: list[str]) -> str:
    """Generate master .mos that loads all column init scripts."""
    lines = [
        "// Master initialization script for ISS columns",
        "// Generated by h2iso flowsheet solver",
        "",
    ]
    for name in column_names:
        script_name = f"{name}_init.mos"
        lines.append(f'runScript("{script_name}");')

    lines.append("")
    lines.append("// Verify initialization")
    lines.append('print("ISS column initialization complete.");')
    lines.append("")
    return "\n".join(lines)


def main():
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description=(
            "Generate Modelica init scripts from h2iso flowsheet solution"
        ),
    )
    parser.add_argument(
        "--config", type=str, required=True,
        help="Path to flowsheet JSON config file",
    )
    parser.add_argument(
        "--output", type=str, default=".",
        help="Output directory for .mos files (default: current)",
    )
    parser.add_argument(
        "--max-iter", type=int, default=50,
        help="Max tear stream iterations (default: 50)",
    )
    parser.add_argument(
        "--tol", type=float, default=1e-4,
        help="Convergence tolerance (default: 1e-4)",
    )
    args = parser.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        print(f"Error: config file not found: {config_path}", file=sys.stderr)
        raise SystemExit(1)

    load_flowsheet, sequential_modular_solver = _load_h2iso_dependencies()

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load and solve flowsheet
    print(f"Loading flowsheet: {config_path}")
    config = load_flowsheet(config_path)
    print(f"  {len(config.columns)} columns, {len(config.feeds)} feeds, "
          f"{len(config.tear_streams)} tear streams")

    print("Solving flowsheet...")
    solver = sequential_modular_solver(
        config,
        method="wegstein",
        continuation_substeps=3,
    )
    result = solver.solve(max_iter=args.max_iter, tol=args.tol)

    if not result.converged:
        print(
            "Warning: flowsheet did not converge "
            f"(residual={result.tear_residual:.2e})",
            file=sys.stderr,
        )

    status = "CONVERGED" if result.converged else "NOT CONVERGED"
    print(f"  Status: {status}, iterations: {result.iterations}")

    # Generate .mos for each column
    column_names = []
    for col_cfg in config.columns:
        col_name = col_cfg.name
        dist_key = f"{col_name}_distillate"
        bot_key = f"{col_name}_bottoms"

        dist_stream = result.streams.get(dist_key)
        bot_stream = result.streams.get(bot_key)

        if dist_stream is None or bot_stream is None:
            print(
                f"  Warning: {col_name} has missing output streams, skipping"
            )
            continue

        mos_content = generate_column_mos(
            col_name=col_name,
            n_stages=col_cfg.n_stages,
            top_composition=dist_stream.composition.tolist(),
            bottom_composition=bot_stream.composition.tolist(),
            top_temperature=float(dist_stream.temperature),
            bottom_temperature=float(bot_stream.temperature),
            distillate_flow=float(dist_stream.flow),
            bottoms_flow=float(bot_stream.flow),
            reflux_ratio=col_cfg.reflux_ratio,
        )

        mos_path = output_dir / f"{col_name}_init.mos"
        mos_path.write_text(mos_content)
        print(f"  Generated: {mos_path}")
        column_names.append(col_name)

    # Generate master init script
    if column_names:
        master_content = generate_init_all_mos(column_names)
        master_path = output_dir / "init_all_columns.mos"
        master_path.write_text(master_content)
        print(f"  Generated: {master_path}")

    # Export summary
    summary = {
        "source_config": str(config_path),
        "converged": result.converged,
        "iterations": result.iterations,
        "columns_initialized": column_names,
    }
    summary_path = output_dir / "init_summary.json"
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2)

    print(
        f"\nDone. {len(column_names)} column init scripts "
        f"generated in {output_dir}/"
    )


if __name__ == "__main__":
    main()
